baseURL = "https://blog.moyrn.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "Moyrne'Blog"
theme = "hermit"

# hermit
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[author]
name = "Moyrne"

[blackfriday]
# hrefTargetBlank = true
# noreferrerLinks = true
# nofollowLinks = true

[taxonomies]
tag = "tags"
# Categories are disabled by default.

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
# Metadata mostly used in document's head
# description = ""
# images = [""]
themeColor = "#494f5c"
homeSubtitle = "一个正在成长的菜鸟."
footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
# bgImg = ""  # Homepage background-image URL
# Prefix of link to the git commit detail page. GitInfo must be enabled.
# gitUrl = "https://github.com/username/repository/commit/"
# Toggling this option needs to rebuild SCSS, requires Hugo extended version
justifyContent = false  # Set "text-align: justify" to `.content`.
relatedPosts = false  # Add a related content section to all single posts page
code_copy_button = true # Turn on/off the code-copy-button for code-fields

[[params.social]]
name = "github"
url = "https://github.com/moyrne"

[params.utteranc]
enable = true
repo = "moyrne/hugo-comment"
issueTerm = "pathname"
theme = "photon-dark"


[menu]
[[menu.main]]
name = "文章"
weight = 200
url = "/blogs/"

[[menu.main]]
name = "标签"
weight = 350
url = "/tags"

[[menu.main]]
name = "关于"
weight = 500
url = "/about"

# anatole
#[params]
#GithubID = "moyrne"
#title = "Moyrne"
#author = "Moyrne"
#description = "一个正在成长的菜鸟"
#profilePicture = "/images/profile.jpg"
#singleDateFormat = "Mon, 2006-01-02"
#indexDateFormat = "Mon, 2006-01-02"
#listDateFormat = "2006-01-02"
#
#[menu]
#[[menu.main]]
#name = "主页"
#identifier = "home"
#weight = 100
#url = "/"
#
#[[menu.main]]
#name = "Kubernetes"
#weight = 200
#identifier = "kubernetes"
#url = "/kubernetes/"
#
#[[menu.main]]
#name = "Golang"
#weight = 203
#identifier = "golang"
#url = "/golang/"
#
#[[menu.main]]
#name = "实用工具"
#weight = 210
#identifier = "tools"
#url = "/tools/"
#
#[[menu.main]]
#name = "关于我"
#weight = 215
#identifier = "about"
#url = "/about"